# Numpy.
    </div>
</div>

In [12]:
import numpy as np

list01 = [[1,2,3],[2,3,4]]
arry = np.array(list01)

print(arry)
arry.ndim

[[1 2 3]
 [2 3 4]]

2

In [13]:
# Create a 1-dimensional array
import numpy as np

oneDarray = np.array([1,2,3])
oneDarray

print(oneDarray.ndim)

1

In [12]:
import numpy as np

OneDArray = np.array([1,2,4,5])
TwoDArray = np.array([[1,2,4,5],[4,5,6,7]])
ThreeDArray = np.array([[[1,2],[3,4],[5,6]]])

npArray

print(OneDArray.ndim)
print(npArray.ndim)
print(ThreeDArray.ndim)

1
2
3

In [15]:
import pandas as pd
array_1d = np.array([1, 2, 3, 4, 5])

print(array_1d)
print("Dimenstion: ",array_1d.ndim)

pd.DataFrame(array_1d)

[1 2 3 4 5]
Dimenstion:  1

   0
0  1
1  2
2  3
3  4
4  5

In [16]:
# Create a 2-dimensional array

array_2d = np.array([[1, 2, 3],[7, 8, 9]])


print(array_2d)
print("Dimenstion: ",array_2d.ndim)

pd.DataFrame(array_2d)

[[1 2 3]
 [7 8 9]]
Dimenstion:  2

   0  1  2
0  1  2  3
1  7  8  9

In [17]:
array_3d = np.array([[[1, 2],
                      [5, 6],
                      [9, 10]]])

print(array_3d)
print("Dimenstion: ",array_3d.ndim)
pd.DataFrame(array_3d)

[[[ 1  2]
  [ 5  6]
  [ 9 10]]]
Dimenstion:  3

ValueError: Must pass 2-d input. shape=(1, 3, 2)

# Important Properties And Attributes of Numpy

<div style="font-family: Arial, sans-serif; max-width: 700px; margin: 10px auto;">

<h3 style="color:#0f172a; border-bottom:2px solid #3b82f6; padding-bottom:6px;">
📊 NumPy Array Attributes
</h3>

<table style="width:100%; border-collapse:collapse;">
    <thead>
        <tr style="background:#3b82f6; color:white;">
            <th style="padding:8px; text-align:left;">Attribute</th>
            <th style="padding:8px; text-align:left;">Description</th>
            <th style="padding:8px; text-align:left;">Example</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding:8px;"><code><b>.shape</b></code></td>
            <td style="padding:8px;">Tuple of array dimensions</td>
            <td style="padding:8px;"><code>(3, 4)</code></td>
        </tr>
        <tr style="background:#f8fafc;">
            <td style="padding:8px;"><code><b>.ndim</b></code></td>
            <td style="padding:8px;">Number of dimensions</td>
            <td style="padding:8px;"><code>2</code></td>
        </tr>
        <tr>
            <td style="padding:8px;"><code><b>.size</b></code></td>
            <td style="padding:8px;">Total number of elements</td>
            <td style="padding:8px;"><code>12</code></td>
        </tr>
        <tr style="background:#f8fafc;">
            <td style="padding:8px;"><code><b>.dtype</b></code></td>
            <td style="padding:8px;">Data type of elements</td>
            <td style="padding:8px;"><code>int64</code></td>
        </tr>
    </tbody>
</table>

<p style="background:#fef3c7; padding:10px; border-left:4px solid #d97706; margin-top:15px;">
💡 <b>Note:</b> These are <b>attributes</b>, not methods. Do not use parentheses <code>()</code>.
</p>

</div> when calling them.
    </div>
</div>

In [37]:
OneDArray = np.array([1,2,3,4])
TwoDArray = np.array([['1','2','4','5'],['4','5','6','7']])
ThreeDArray = np.array([[[1,2],[3,4],[5,6]]])

print(OneDArray)
print(OneDArray.shape)
print(OneDArray.ndim)
print(OneDArray.size)
print(OneDArray.dtype)

[1 2 3 4]
(4,)
1
4
int32

In [31]:
print(TwoDArray)
print(TwoDArray.shape)
print(TwoDArray.ndim)
print(TwoDArray.size)
print(TwoDArray.dtype)

[['1' '2' '4' '5']
 ['4' '5' '6' '7']]
(2, 4)
2
8
<U1

In [33]:
print(ThreeDArray)
print(ThreeDArray.shape)
print(ThreeDArray.ndim)
print(ThreeDArray.size)
print(ThreeDArray.dtype)

[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)
3
6
int32

[[[[1 2]
   [3 4]
   [5 6]
   [5 6]]]]
(1, 1, 4, 2)
4
8
int32

In [38]:
# Shape
# to check shape of an array
array_2d = np.array([[1, 2, 3,4], 
                     [4, 5, 6,4], 
                     [7, 8, 9,10]])
print(array_2d.shape)

(3, 4)

In [28]:
arr1 = np.array([1, 2, 3])
arr1.shape

(3,)

In [39]:
# ndim
# to check dimesnion of an array

array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.ndim)

2

In [30]:
# size
# to check the size
import numpy as np

array_2d = np.array([[1, 2, 3,6], 
                     [4, 5, 6,8], 
                     [7, 8, 9,9]])

print(array_2d.size)

12

In [6]:
# dtype
# to know the type of an array

array_2d.dtype

dtype('int32')

# Type Convestion / Casting

In [52]:
# astype
# type casting in array
# if you want change the data type

array_2d = np.array([[1, 2, 3,6], 
                     [4, 5, 6,8], 
                     [7, 8, 9,9]])

print(array_2d.dtype)
newArr = array_2d.astype('float')
print(newArr.dtype)
newArr = newArr.astype('str')
print(newArr)
newArr.dtype

int32
float64
[['1.0' '2.0' '3.0' '6.0']
 ['4.0' '5.0' '6.0' '8.0']
 ['7.0' '8.0' '9.0' '9.0']]

dtype('<U32')

In [ ]:
array_2d = array_2d.astype('int')
print(array_2d.dtype)

# Functions in Numpy

<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 10px auto;">

<h3 style="color:#0f172a; border-bottom:2px solid #3b82f6; padding-bottom:6px;">
📊 Common NumPy Array Creation Functions
</h3>

<table style="width:100%; border-collapse:collapse;">
<thead>
<tr style="background:#3b82f6; color:white;">
<th style="padding:8px; text-align:left;">Function</th>
<th style="padding:8px; text-align:left;">Description</th>
<th style="padding:8px; text-align:left;">Examples</th>
</tr>
</thead>

<tbody>

<tr>
<td style="padding:8px;"><code><b>np.zeros()</b></code></td>
<td style="padding:8px;">Creates an array filled with zeros</td>
<td style="padding:8px;">
<code>np.zeros(5)</code><br>
<code>np.zeros((3,5))</code>
</td>
</tr>

<tr style="background:#f8fafc;">
<td style="padding:8px;"><code><b>np.ones()</b></code></td>
<td style="padding:8px;">Creates an array filled with ones</td>
<td style="padding:8px;">
<code>np.ones(5)</code><br>
<code>np.ones((3,5))</code>
</td>
</tr>

<tr>
<td style="padding:8px;"><code><b>np.eye()</b></code></td>
<td style="padding:8px;">Creates an identity matrix</td>
<td style="padding:8px;">
<code>np.eye(4)</code><br>
<code>np.eye(2,3)</code>
</td>
</tr>

<tr style="background:#f8fafc;">
<td style="padding:8px;"><code><b>np.diag()</b></code></td>
<td style="padding:8px;">Creates a diagonal matrix from values</td>
<td style="padding:8px;">
<code>np.diag([2,3,4])</code>
</td>
</tr>

<tr>
<td style="padding:8px;"><code><b>np.random.randint()</b></code></td>
<td style="padding:8px;">Generates random integers within a range</td>
<td style="padding:8px;">
<code>np.random.randint(1,5)</code>
</td>
</tr>

<tr style="background:#f8fafc;">
<td style="padding:8px;"><code><b>np.arange()</b></code></td>
<td style="padding:8px;">Generates evenly spaced values within a range</td>
<td style="padding:8px;">
<code>np.arange(0,10)</code>
</td>
</tr>

</tbody>
</table>

<p style="background:#fef3c7; padding:10px; border-left:4px solid #d97706; margin-top:15px;">
💡 <b>Tip:</b> Use <code>np.zeros()</code> and <code>np.ones()</code> for initialization, <code>np.eye()</code> and <code>np.diag()</code> for matrices, <code>np.random.randint()</code> for random values, and <code>np.arange()</code> for sequences.
</p>

</div>r random numbers, and <code>np.arange()</code> for sequences.
</p>

</div>

In [82]:
print(range(1,10))
print(np.arange(1,10))

range(1, 10)
[1 2 3 4 5 6 7 8 9]

In [10]:
# zeros
# Create one Dimenstion Arrays

np.zeros((5))

array([0., 0., 0., 0., 0.])

In [11]:
# zeros 
# create n-Dimenstion Arrays

abc = np.zeros((3,4))
print(abc.ndim)
print(abc)

2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [14]:
# Ones 
# create one Dimenstion Arrays

arr_ones = np.ones((2,5))
print(arr_ones.ndim)
print()
print(arr_ones)

2

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [15]:
# Ones 
# create n-Dimenstion Arrays

arr_ones = np.ones((2,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]]

In [19]:
# eye
identity_matrix = np.eye(4)
print(identity_matrix.ndim)
print(identity_matrix)

2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [21]:
# eye
identity_matrix = np.eye(2,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]

In [23]:
# diag
diagonalArray = np.diag([2,3,4])
diagonalArray

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [6]:
# generate random Numbers
np.random.randint(1,5)

4

In [36]:
# generate random Numbers
np.random.randint(1,10,3)

array([6, 6, 3])

In [7]:
# Create a range of values
arr_range = np.arange(0, 10)
print(arr_range)

[0 1 2 3 4 5 6 7 8 9]

In [38]:
# Create a range of values
arr_range = np.arange(0,11,2)
print(arr_range)

[ 0  2  4  6  8 10]

# Indexing and slicing

In [57]:

array_1d = np.array([8, 9, 10, 11, 12])
#index               0  1   2  3  4
#index              -5 -4  -3 -2 -1

array_1d[1:3]

array([ 9, 10])

# Iterating over Numpy

<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 10px auto;">

<h3 style="color:#0f172a; border-bottom:2px solid #3b82f6; padding-bottom:6px;">
🔄 NumPy Array Iteration Methods
</h3>

<table style="width:100%; border-collapse:collapse;">
<thead>
<tr style="background:#3b82f6; color:white;">
<th style="padding:8px; text-align:left;">Method</th>
<th style="padding:8px; text-align:left;">Description</th>
<th style="padding:8px; text-align:left;">Example</th>
</tr>
</thead>

<tbody>

<tr>
<td style="padding:8px;"><code><b>for i in arr</b></code></td>
<td style="padding:8px;">Iterates over each row (or element in a 1D array)</td>
<td style="padding:8px;">
<code>for i in arr:<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>
</td>
</tr>

<tr style="background:#f8fafc;">
<td style="padding:8px;"><code><b>for i in arr.T</b></code></td>
<td style="padding:8px;">Iterates over each column using the transpose of the array</td>
<td style="padding:8px;">
<code>for i in arr.T:<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>
</td>
</tr>

<tr>
<td style="padding:8px;"><code><b>np.nditer()</b></code></td>
<td style="padding:8px;">Iterates through every element regardless of array dimensions</td>
<td style="padding:8px;">
<code>for element in np.nditer(arr):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(element)</code>
</td>
</tr>

</tbody>
</table>

<p style="background:#fef3c7; padding:10px; border-left:4px solid #d97706; margin-top:15px;">
💡 <b>Tip:</b> Use <code>arr</code> to iterate row-wise, <code>arr.T</code> to iterate column-wise, and <code>np.nditer()</code> when you need to access every element in a multidimensional array.
</p>

</div>

In [94]:

oneDarr = np.array([1, 2, 3])

twoDarr = np.array([[1, 2, 3],
                    [4, 5, 6]])

for i in np.nditer(twoDarr):
    print(i)

1
2
3
4
5
6

In [43]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over each element in the array
for i in arr:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]

In [ ]:
arr.T

In [44]:
# Iterate over each column

for i in arr.T:
    print(i)

[1 4 7]
[2 5 8]
[3 6 9]

In [45]:
# Iterate over each element using np.nditer()
for element in np.nditer(arr):
    print(element)

1
2
3
4
5
6
7
8
9

# Operations in Array

<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 10px auto;">

<h3 style="color:#0f172a; border-bottom:2px solid #3b82f6; padding-bottom:6px;">
🧮 NumPy Array Operations & Statistics
</h3>

<table style="width:100%; border-collapse:collapse;">
<thead>
<tr style="background:#3b82f6; color:white;">
<th style="padding:8px; text-align:left;">Operation</th>
<th style="padding:8px; text-align:left;">Description</th>
<th style="padding:8px; text-align:left;">Examples</th>
</tr>
</thead>

<tbody>

<tr>
<td style="padding:8px;"><code><b>Arithmetic Operations</b></code></td>
<td style="padding:8px;">Perform element-wise mathematical operations between arrays</td>
<td style="padding:8px;">
<code>arr2 - arr1</code><br>
<code>arr1 + arr2</code><br>
<code>arr1 * arr2</code><br>
<code>arr1 / arr2</code>
</td>
</tr>

<tr style="background:#f8fafc;">
<td style="padding:8px;"><code><b>Comparison Operations</b></code></td>
<td style="padding:8px;">Returns a Boolean array based on the condition</td>
<td style="padding:8px;">
<code>arr1 >= 3</code>
</td>
</tr>

<tr>
<td style="padding:8px;"><code><b>Aggregation Functions</b></code></td>
<td style="padding:8px;">Returns summary statistics of the array</td>
<td style="padding:8px;">
<code>arr.max()</code><br>
<code>arr.min()</code><br>
<code>np.median(arr)</code>
</td>
</tr>

</tbody>
</table>

<p style="background:#fef3c7; padding:10px; border-left:4px solid #d97706; margin-top:15px;">
💡 <b>Tip:</b> NumPy performs arithmetic and comparison operations element-wise. Use aggregation functions like <code>max()</code>, <code>min()</code>, and <code>median()</code> to quickly summarize array data.
</p>

</div>

In [109]:
arr1 = np.array([1,2,6,4,5,6])
arr2 = np.array([4,5,6,7,8,15])

np.median(arr2)

6.5

In [48]:
# substraction
print(arr2)

print(arr1)

print(arr2-arr1)

[ 4  5  6  7  8 15]
[1 2 3 4 5 6]
[3 3 3 3 3 9]

In [49]:
# Addition
arr1+arr2

array([ 5,  7,  9, 11, 13, 21])

In [50]:
# Multipication
arr1*arr2

array([ 4, 10, 18, 28, 40, 90])

In [51]:
# Division
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.4       ])

In [54]:
# Comparision

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

arr1>=3

[1 2 3 4 5 6]

array([False, False,  True,  True,  True,  True])

In [56]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# max 
# 0 = row
# 1 = column


array_2d.max()
print(array_2d.max(axis=0))
print(array_2d.max(axis=1))

[7 8 9]
[3 6 9]

In [60]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

print(array_2d.min())

print(array_2d.min(axis=0))

print(array_2d.min(axis=1))

1
[1 2 3]
[1 4 7]

In [61]:
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])


print(array_2d.mean())
print(array_2d.mean(axis=0))
print(array_2d.mean(axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]

In [62]:

print(array_2d.std())
print(array_2d.std(axis=0))
print(array_2d.std(axis=1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]

In [63]:

print(np.median(array_2d))
print(np.median(array_2d,axis=0))
print(np.median(array_2d,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]

# Deep Dive Reshaping

In [116]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8,9])

arr_1d

arr_1d.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
newArray = arr_1d.reshape(2, 5)
newArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
newArray = arr_1d.reshape(5, 2)
newArray

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [118]:
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

newArray = arr_1d.reshape(4, 3)
newArray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [120]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr1

arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# ravel : to change the shape of an array from n dimesion to 1D 

arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr1 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

arr1 = arr1.transpose()

df = pd.DataFrame(arr1)

df

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [71]:
# transpose : changing row to Column and Column to Row 
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [129]:
# stacking : combining two different array to one array
# hstack 

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

newArr = np.hstack([arr1,arr2])

np.unique(newArr)

df.unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
# vstack
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr3 = np.array([4,5,6,7,8,9])
arr4 = np.array([4,5,6,7,8,9])
arr5 = np.array([4,5,6,7,8,9])


np.vstack((arr1,arr2,arr3,arr4,arr5))

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [133]:
np.hstack((arr1,arr2,arr3,arr4,arr5))

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7,
       8, 9, 4, 5, 6, 7, 8, 9])

In [136]:
# splitting an array
# hsplit

arr1 = np.array([1,2,3,4,5,6,7,8])

np.hsplit(arr1,4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [138]:
# splitting an array
# vsplit
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

np.vsplit(array_2d,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]