# <h1 style="color:#2a9d8f; font-family:Candara, sans-serif; text-align:left; margin:-60px 0 0 0; padding:0;">Type of Filtering</h1>
<ul style="color:#2a9d8f; font-family:Candara, sans-serif; font-size:15px; line-height:1.2; margin:0 0 0 20px; padding:0;">
    <li><b>Simple Filtering</b></li>
    <li><b>Conditional Filtering</b></li>
    <li><b>Single Value Filtering</b></li>
</ul>

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: left; margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;">Single Value Filtering 
</h2>


<p style="color:#264653; font-family:Candara, sans-serif; font-size:17px; margin:0; padding-top:10px;">
Below is the list of ways you can filter the datasets:
</p>

<ol style="font-family:Candara, sans-serif; font-size:17px; margin:0 0 0 20px; padding:0; list-style-type:none;">
    <li style="color:#2a9d8f;"><b>.at</b>
        <p style="color:#2a9d8f; font-family:Candara, sans-serif; font-size:16px; margin:0;">
            <i>Description:</i> Label-based, used to access a single value by row and column labels.<br>
            <i>Syntax:</i> <code>df.at[rowNumber, columnName]</code><br>
            <i>Example:</i> <code>df.at[2, "FirstName"]</code>
        </p>
    </li>
    <li style="color:#2a9d8f;"><b>.iat</b>
        <p style="color:#2a9d8f; font-family:Candara, sans-serif; font-size:16px; margin:0;">
            <i>Description:</i> Integer position-based, used to access a single value by row and column positions.<br>
            <i>Syntax:</i> <code>df.iat[rowNumber, columnNumber]</code><br>
            <i>Example:</i> <code>df.iat[2, 3]</code>
        </p>
    </li>
</ol>
</p>
    </li>
</ol>

   </p>
    </li>
</ol>

In [ ]:
# Colums Filtering

In [10]:

import pandas as pd

file_path = "D:/Old Projects/MLProjects/ZDatasets/DummyData/Data_Train1.csv"
df = pd.read_csv(file_path)

df

df.columns

Index(['First_name', 'Last_name', 'Age', 'City', 'Airline', 'Date_of_Journey',
       'Dep_Time', 'Airfare', 'Full Name'],
      dtype='object')

In [9]:
Cond01Columns = df.columns == "Airfare"


df.columns == 'Age', 'City'

(array([False, False,  True, False, False, False, False, False, False]),
 'City')

In [10]:
df = df.loc[:, Cond01Columns]

df

   Airfare
0  8715.10
1  8715.10
2     0.00
3  6995.55
4  7840.56
5  7813.89
6  7840.56
7  7813.89

In [12]:
Condi01 = df.columns.str.startswith('A')

df = df.loc[:, Condi01]
df

    Age      Airline  Airfare
0  42.0          NaN  8715.10
1  42.0       IndiGo  8715.10
2  52.0    Air India     0.00
3  36.0  Jet Airways  6995.55
4   NaN       IndiGo  7840.56
5   NaN       IndiGo  7813.89
6   NaN       IndiGo  7840.56
7   NaN       IndiGo  7813.89

# <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataFrame Iteration</title>
    <style>
        /* Define the primary colors used in the original example */
        .color-primary { color: #2a9d8f; } /* Teal/Green */
        .color-secondary { color: #264653; } /* Dark Blue/Gray */
        .font-candara { font-family: 'Candara', sans-serif; }
    </style>
</head>
<body>

<h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; fonttext-align: left; margin:-60px 0 0 0;xt-align: left; padding-bottom: 10px; border-bottom: 2px solid #264653;">Iteration over DataFrame</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 12px; line-height: 1.5; margin-top: 20px;">
    Iterating over a DataFrame can be done in several ways depending on your needs. Here are some common methods:
</p>


<ol style="font-family: 'Candara', sans-serif; font-size: 12px; line-height: 1.5; padding-left: 20px; margin-top: 10px; list-style-type: none;">
    <li style="color: #2a9d8f; margin-bottom: 5px;">
        <b>Using <code>iterrows()</code></b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 15px; margin: 0; line-height: 1.2;">
            Iterate over DataFrame rows as (index, Series) pairs.<br>
            <i>Syntax:</i> <code>for index, row in df.iterrows():</code>
        </p>
    </li>
    <li style="color: #2a9d8f; margin-bottom: 5px;">
        <b>Using <code>itertuples()</code></b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 15px; margin: 0; line-height: 1.2;">
            Iterate over DataFrame rows as named tuples (Generally faster than <code>iterrows()</code>).<br>
            <i>Syntax:</i> <code>for row in df.itertuples():</code>
        </p>
    </li>
    <li style="color: #2a9d8f;">
        <b>Using <code>items()</code></b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 15px; margin: 0; line-height: 1.2;">
            Iterate over DataFrame columns as (column\_name, Series) pairs.<br>
            <i>Syntax:</i> <code>for column_name, series in df.items():</code>
        </p>
    </li>
</ol>

</body>
</html>     </p>
    </li>
</ol>

</body>
</html>"syntax">for column_name, series in df.items():</span>
        </li>
    </ol>

</body>
</html>
     </p>
    </li>
</ol>

</body>
</html>      </p>
    </li>
</ol>

</body>
</html>

In [ ]:
df

In [13]:
import pandas as pd
# print(os.path.exists("D:/DataSets/01_AirlineData/Airline.csv"))



file_path = "D:/Old Projects/MLProjects/ZDatasets/DummyData/Data_Train1.csv"
df = pd.read_csv(file_path)

df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Airfare,Full Name
0,Rajesh,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,8715.10,Ram-Kumar
1,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,8715.10,Ram-Kumar
2,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,0.00,Mohan-Sharma
3,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,6995.55,Tina-Ali
4,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
5,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari
6,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
7,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari

True

In [15]:
'''Iterrows'''
for index, row in df.iterrows():
    print(index)
    print(row)
    print()

0
First_name             Rajesh
Last_name               Kumar
Age                      42.0
City                BANGALURU
Airline                   NaN
Date_of_Journey    24-03-2019
Dep_Time                22:20
Airfare                8715.1
Full Name           Ram-Kumar
Name: 0, dtype: object

1
First_name                Ram
Last_name               Kumar
Age                      42.0
City                BANGALURU
Airline                IndiGo
Date_of_Journey    24-03-2019
Dep_Time                22:20
Airfare                8715.1
Full Name           Ram-Kumar
Name: 1, dtype: object

2
First_name                Mohan
Last_name                Sharma
Age                        52.0
City                    CHENNAI
Airline               Air India
Date_of_Journey      01-05-2019
Dep_Time                  05:50
Airfare                     0.0
Full Name          Mohan-Sharma
Name: 2, dtype: object

3
First_name                Tina
Last_name                  Ali
Age                       36.0
City                      Pune
Airline            Jet Airways
Date_of_Journey     09-06-2019
Dep_Time                 09:25
Airfare                6995.55
Full Name             Tina-Ali
Name: 3, dtype: object

4
First_name                Jeetu
Last_name                Gandhi
Age                         NaN
City                      Delhi
Airline                  IndiGo
Date_of_Journey      12-05-2019
Dep_Time                  18:05
Airfare                 7840.56
Full Name          Jeetu-Gandhi
Name: 4, dtype: object

5
First_name                Meera
Last_name                Kumari
Age                         NaN
City                    LUCKNOW
Airline                  IndiGo
Date_of_Journey      01-03-2019
Dep_Time                  16:50
Airfare                 7813.89
Full Name          Meera-Kumari
Name: 5, dtype: object

6
First_name                Jeetu
Last_name                Gandhi
Age                         NaN
City                      Delhi
Airline                  IndiGo
Date_of_Journey      12-05-2019
Dep_Time                  18:05
Airfare                 7840.56
Full Name          Jeetu-Gandhi
Name: 6, dtype: object

7
First_name                Meera
Last_name                Kumari
Age                         NaN
City                    LUCKNOW
Airline                  IndiGo
Date_of_Journey      01-03-2019
Dep_Time                  16:50
Airfare                 7813.89
Full Name          Meera-Kumari
Name: 7, dtype: object

In [172]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Airfare,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,8715.10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,0.00,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,6995.55,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari

In [16]:
'''Using items'''
for colNmae, colValue in df.items():
    print(colNmae)
    print(colValue)
    print()
    print()

First_name
0    Rajesh
1       Ram
2     Mohan
3      Tina
4     Jeetu
5     Meera
6     Jeetu
7     Meera
Name: First_name, dtype: object


Last_name
0     Kumar
1     Kumar
2    Sharma
3       Ali
4    Gandhi
5    Kumari
6    Gandhi
7    Kumari
Name: Last_name, dtype: object


Age
0    42.0
1    42.0
2    52.0
3    36.0
4     NaN
5     NaN
6     NaN
7     NaN
Name: Age, dtype: float64


City
0    BANGALURU
1    BANGALURU
2      CHENNAI
3         Pune
4        Delhi
5      LUCKNOW
6        Delhi
7      LUCKNOW
Name: City, dtype: object


Airline
0            NaN
1         IndiGo
2      Air India
3    Jet Airways
4         IndiGo
5         IndiGo
6         IndiGo
7         IndiGo
Name: Airline, dtype: object


Date_of_Journey
0    24-03-2019
1    24-03-2019
2    01-05-2019
3    09-06-2019
4    12-05-2019
5    01-03-2019
6    12-05-2019
7    01-03-2019
Name: Date_of_Journey, dtype: object


Dep_Time
0    22:20
1    22:20
2    05:50
3    09:25
4    18:05
5    16:50
6    18:05
7    16:50
Name: Dep_Time, dtype: object


Airfare
0    8715.10
1    8715.10
2       0.00
3    6995.55
4    7840.56
5    7813.89
6    7840.56
7    7813.89
Name: Airfare, dtype: float64


Full Name
0       Ram-Kumar
1       Ram-Kumar
2    Mohan-Sharma
3        Tina-Ali
4    Jeetu-Gandhi
5    Meera-Kumari
6    Jeetu-Gandhi
7    Meera-Kumari
Name: Full Name, dtype: object

In [174]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Airfare,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,8715.10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,0.00,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,6995.55,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari

In [21]:
'''Using itertuples'''
for i in df.itertuples():
    print(i)
    for j in i:
        print(j)
    print()

Pandas(Index=0, First_name='Rajesh', Last_name='Kumar', Age=42.0, City='BANGALURU', Airline=nan, Date_of_Journey='24-03-2019', Dep_Time='22:20', Airfare=8715.1, _9='Ram-Kumar')
0
Rajesh
Kumar
42.0
BANGALURU
nan
24-03-2019
22:20
8715.1
Ram-Kumar

Pandas(Index=1, First_name='Ram', Last_name='Kumar', Age=42.0, City='BANGALURU', Airline='IndiGo', Date_of_Journey='24-03-2019', Dep_Time='22:20', Airfare=8715.1, _9='Ram-Kumar')
1
Ram
Kumar
42.0
BANGALURU
IndiGo
24-03-2019
22:20
8715.1
Ram-Kumar

Pandas(Index=2, First_name='Mohan', Last_name='Sharma', Age=52.0, City='CHENNAI', Airline='Air India', Date_of_Journey='01-05-2019', Dep_Time='05:50', Airfare=0.0, _9='Mohan-Sharma')
2
Mohan
Sharma
52.0
CHENNAI
Air India
01-05-2019
05:50
0.0
Mohan-Sharma

Pandas(Index=3, First_name='Tina', Last_name='Ali', Age=36.0, City='Pune', Airline='Jet Airways', Date_of_Journey='09-06-2019', Dep_Time='09:25', Airfare=6995.55, _9='Tina-Ali')
3
Tina
Ali
36.0
Pune
Jet Airways
09-06-2019
09:25
6995.55
Tina-Ali

Pandas(Index=4, First_name='Jeetu', Last_name='Gandhi', Age=nan, City='Delhi', Airline='IndiGo', Date_of_Journey='12-05-2019', Dep_Time='18:05', Airfare=7840.56, _9='Jeetu-Gandhi')
4
Jeetu
Gandhi
nan
Delhi
IndiGo
12-05-2019
18:05
7840.56
Jeetu-Gandhi

Pandas(Index=5, First_name='Meera', Last_name='Kumari', Age=nan, City='LUCKNOW', Airline='IndiGo', Date_of_Journey='01-03-2019', Dep_Time='16:50', Airfare=7813.89, _9='Meera-Kumari')
5
Meera
Kumari
nan
LUCKNOW
IndiGo
01-03-2019
16:50
7813.89
Meera-Kumari

Pandas(Index=6, First_name='Jeetu', Last_name='Gandhi', Age=nan, City='Delhi', Airline='IndiGo', Date_of_Journey='12-05-2019', Dep_Time='18:05', Airfare=7840.56, _9='Jeetu-Gandhi')
6
Jeetu
Gandhi
nan
Delhi
IndiGo
12-05-2019
18:05
7840.56
Jeetu-Gandhi

Pandas(Index=7, First_name='Meera', Last_name='Kumari', Age=nan, City='LUCKNOW', Airline='IndiGo', Date_of_Journey='01-03-2019', Dep_Time='16:50', Airfare=7813.89, _9='Meera-Kumari')
7
Meera
Kumari
nan
LUCKNOW
IndiGo
01-03-2019
16:50
7813.89
Meera-Kumari

In [22]:
'''Using Index'''

for i in df.index:
    print(df['First_name'][i],df['Last_name'][i])

Rajesh Kumar
Ram Kumar
Mohan Sharma
Tina Ali
Jeetu Gandhi
Meera Kumari
Jeetu Gandhi
Meera Kumari

In [197]:
for i in df.index:
    print(df.loc[i,['First_name']])

First_name    Ram
Name: 0, dtype: object
First_name    Mohan
Name: 1, dtype: object
First_name    Tina
Name: 2, dtype: object
First_name    Jeetu
Name: 3, dtype: object
First_name    Meera
Name: 4, dtype: object

In [202]:
for i in df.index:
    print(df.iloc[i,[0]])

First_name    Ram
Name: 0, dtype: object
First_name    Mohan
Name: 1, dtype: object
First_name    Tina
Name: 2, dtype: object
First_name    Jeetu
Name: 3, dtype: object
First_name    Meera
Name: 4, dtype: object

In [203]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Airfare,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,8715.10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,0.00,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,6995.55,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari

# <h2 style="color:#2a9d8f; font-family:'Candara', sans-serif; font-weight:bold; text-align:left; margin:-60px 0 0 0; padding-bottom:10px; border-bottom:2px solid #264653;">Concatenation, Joining, and Merging Operations in Pandas</h2>s
</h2>
</li>

</ol>

</body>
</html>
>
</ol>
/p>
    </li>
</ol>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 15px; line-height: 1.5; margin-top: 15px;">
Combining DataFrames can be achieved through concatenation, joining, and merging. Here are the common methods:
</p>

<ol style="font-family: 'Candara', sans-serif; font-size: 15px; line-height: 1.5; padding-left: 20px; margin-top: 10px; list-style-type: none;">

<li style="color: #2a9d8f; margin-bottom: 10px;">
<b>Concatenation</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
Combine multiple DataFrames along rows or columns using <code>pd.concat()</code>.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
<i>Syntax:</i> <br>
<code>pd.concat([df1, df2, df3], axis=0)</code> &nbsp;# axis=0 for rows<br>
<code>pd.concat([df1, df2, df3], axis=1)</code> &nbsp;# axis=1 for columns
</p>
</li>

<li style="color: #2a9d8f; margin-bottom: 10px;">
<b>Merging</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
Combine DataFrames based on common columns or keys using <code>pd.merge()</code>.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
<i>Syntax:</i><br>
<code>pd.merge(df1, df2, left_on='name1', right_on='name2', how='outer')</code><br>
Join types: <code>how='outer'</code> | <code>how='inner'</code> | <code>how='left'</code> | <code>how='right'</code>
</p>
</li>

<li style="color: #2a9d8f;">
<b>Joining</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
Join DataFrames using their indices with <code>df1.join(df2)</code>.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height: 1.2;">
<i>Syntax:</i><br>
<code>df1.join(df2, how='outer')</code><br>
Join types: <code>how='outer'</code> | <code>how='inner'</code> | <code>how='left'</code> | <code>how='right'</code>
</p>
</li>

</ol>

</body>
</html>
>
</ol>
/p>
    </li>
</ol>

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: center; padding-bottmargin:-60px 0 0 0;om: 10px; border-bottom: 2px solid #264653;">Concatenation in Pandas</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    Concatenation is used to combine DataFrames along a specific axis. Here are the common methods for concatenating DataFrames:
</p>

<ol style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; paddingleft: 20px; margin-top: 10px; list-style-type: noon</b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 16px; margin: 0;">
            To concatenate DataFrames along rows: <code>pd.concat([df1, df2, df3], axis=0)</code><br>
            To concatenate DataFrames along columns: <code>pd.concat([df1, df2, df3], axis=1)</code>
        </p>
    </li>
</ol>
    </li>
</ol>
11

   </div>
        </div>
    </div>
</div>   </li>
    </ul>
</div>

In [22]:
import pandas as pd

df1 = pd.DataFrame(
        {"A": ["A0", "A1", "A2", "A3"],
            "B": ["B0", "B1", "B2", "B3"],
        },
        index=[0, 1, 2, 3],
    )
    

df2 = pd.DataFrame(
        {   "A": ["A0", "A1", "A2", "A3"],
            "B": ["B4", "B5", "B6", "B7"],
                 },
        index=[4, 5, 6, 7],
    )
    

df3 = pd.DataFrame({"A": ["A0", "A1", "A2", "A3"],
                    "B": ["B8", "B9", "B10", "B11"],},
                    index=[8, 9, 10, 11],)

print(df1)
print()
print(df2)
print()
print(df3)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

    A   B
4  A0  B4
5  A1  B5
6  A2  B6
7  A3  B7

     A    B
8   A0   B8
9   A1   B9
10  A2  B10
11  A3  B11

In [ ]:
# Concant dataframe can be joined vertically or horizontally but no outer, inner, left or right join are possible

In [23]:
'''Join Dataframe on top of the above '''
allDf = [df1,df2,df3]
# row = 0
# column = 1
pd.concat(allDf,axis=0)

     A    B
0   A0   B0
1   A1   B1
2   A2   B2
3   A3   B3
4   A0   B4
5   A1   B5
6   A2   B6
7   A3   B7
8   A0   B8
9   A1   B9
10  A2  B10
11  A3  B11

In [52]:
'''Join Dataframe Side by Side '''
allDf = [df1,df2,df3]
# row = 0
# column = 1
pd.concat(allDf,axis=1)

      A    B    A    B    A    B
0    A0   B0  NaN  NaN  NaN  NaN
1    A1   B1  NaN  NaN  NaN  NaN
2    A2   B2  NaN  NaN  NaN  NaN
3    A3   B3  NaN  NaN  NaN  NaN
4   NaN  NaN   A0   B4  NaN  NaN
5   NaN  NaN   A1   B5  NaN  NaN
6   NaN  NaN   A2   B6  NaN  NaN
7   NaN  NaN   A3   B7  NaN  NaN
8   NaN  NaN  NaN  NaN   A0   B8
9   NaN  NaN  NaN  NaN   A1   B9
10  NaN  NaN  NaN  NaN   A2  B10
11  NaN  NaN  NaN  NaN   A3  B11

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: center;margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;">Join Types in Pandas</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    Different join types determine which rows are included in the result:
</p>

<ul style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: none;">
    <li style="color: #2a9d8f;"><b>Outer Join</b>: Includes all rows from both DataFrames.<br>
        <code>how='outer'</code>
    </li>
    <li style="color: #2a9d8f;"><b>Inner Join</b>: Includes only rows with matching keys in both DataFrames.<br>
        <code>how='inner'</code>
    </li>
    <li style="color: #2a9d8f;"><b>Left Join</b>: Includes all rows from the left DataFrame and matching rows from the right.<br>
        <code>how='left'</code>
    </li>
    <li style="color: #2a9d8f;"><b>Right Join</b>: Includes all rows from the right DataFrame and matching rows from the left.<br>
        <code>how='right'</code>
    </li>
</ul>
li>
</ul>

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: center;margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;">Merging DataFrames in Pandas</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    Merging DataFrames combines them based on common columns or indices. Here’s how different join types work:
</p>

<ol style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: none;">
    <li style="color: #2a9d8f;"><b>Outer Join</b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 16px; margin: 0;">
            Includes all rows from both DataFrames, with `NaN` for non-matching rows.<br>
            <code>pd.merge(df1, df2, left_on='name1', right_on='name2', how='outer')</code>
        </p>
</ol>

In [55]:
#  Create DataFrame

data1 = [("Alice", 1),("Charlie", 2),("Bob", 3)]
columns1 = ["name1", "value1"]

df1 = pd.DataFrame(data1, columns=columns1)
print(df1)

print()

data2 = [("Alice", 10), ("Bob", 20), ("David", 30)]
columns2 = ["name2", "value2"]
df2 = pd.DataFrame(data2, columns=columns2)
print(df2)

     name1  value1
0    Alice       1
1  Charlie       2
2      Bob       3

   name2  value2
0  Alice      10
1    Bob      20
2  David      30

In [ ]:
# outer = 
# inner
# left
# right

In [56]:
# merge()
# Outer join
# in merge method common_key is considered

# pd.merge(df1, df2, left_on='NameOfCol', right_on='NameOfCol', how='outer')

pd.merge(df1,df2,left_on='name1',right_on='name2',how='outer')

     name1  value1  name2  value2
0    Alice     1.0  Alice    10.0
1  Charlie     2.0    NaN     NaN
2      Bob     3.0    Bob    20.0
3      NaN     NaN  David    30.0

In [57]:
# inner join
# in merge method common_key is considered

merged_df = pd.merge(df1, df2, left_on='name1', right_on='name2',how='inner')
merged_df

   name1  value1  name2  value2
0  Alice       1  Alice      10
1    Bob       3    Bob      20

In [58]:
# left join
# in merge method common_key is considered

merged_df = pd.merge(df1, df2, left_on='name1', right_on='name2',how='left')
merged_df

     name1  value1  name2  value2
0    Alice       1  Alice    10.0
1  Charlie       2    NaN     NaN
2      Bob       3    Bob    20.0

In [59]:
# right join
# in merge method common_key is considered

merged_df = pd.merge(df1, df2, left_on='name1', right_on='name2',how='right')
merged_df

   name1  value1  name2  value2
0  Alice     1.0  Alice      10
1    Bob     3.0    Bob      20
2    NaN     NaN  David      30

In [60]:
#  Create DataFrame

data1 = [("Alice", 1),("Charlie", 2),("Bob", 3)]
columns1 = ["name", "value1"]

df1 = pd.DataFrame(data1, columns=columns1)
df1.set_index('name', inplace=True)

df1

         value1
name
Alice         1
Charlie       2
Bob           3

In [61]:
data2 = [("Alice", 10), ("Bob", 20), ("David", 30)]
columns2 = ["name", "value2"]

df2 = pd.DataFrame(data2, columns=columns2)
df2.set_index('name', inplace=True)

df2

       value2
name
Alice      10
Bob        20
David      30

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: center;margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;">Joining DataFrames by Index in Pandas</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    Joining DataFrames based on their indices combines the DataFrames based on index values. Before performing the join operation, follow these steps:
</p>

<ol style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: none;">
    <li style="color: #2a9d8f;"><b>Convert Columns to Index</b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 16px; margin: 0;">
            Use <code>set_index()</code> to convert the relevant columns to indices:
        </p>
        <pre><code>df1.set_index('column_name', inplace=True)
df2.set_index('column_name', inplace=True)
</code></pre>
    </li>
    <li style="color: #2a9d8f;"><b>Perform the Join Operation</b>
        <p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 16px; margin: 0;">
            Use the following syntax for an outer 
            join:
            <code>df1.join(df2, how='outer')</code>
        </p>
    </li>
</ol>
ue)
</code></pre>
n_name', inplace=True)
</code></pre>
        </p>
    </li>
</ol>

In [62]:
# join()
# Outer join

merged_df = df1.join(df2,how='outer')
merged_df

         value1  value2
name
Alice       1.0    10.0
Bob         3.0    20.0
Charlie     2.0     NaN
David       NaN    30.0

In [63]:
# join()
# inner join
# in merge method common_key is considered

merged_df = df1.join(df2,how='inner')
merged_df

       value1  value2
name
Alice       1      10
Bob         3      20

In [64]:
# join()
# left join
# in merge method common_key is considered

merged_df = df1.join(df2,how='left')
merged_df

         value1  value2
name
Alice         1    10.0
Charlie       2     NaN
Bob           3    20.0

In [65]:
# join()
# Outer join
# in merge method common_key is considered

merged_df = df1.join(df2,how='right')
merged_df

       value1  value2
name
Alice     1.0      10
Bob       3.0      20
David     NaN      30

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: left; margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;">Pivot in Pandas</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    In Pandas, the <code>pivot</code> method is used to reshape data based on column values. It allows you to transform or pivot data from a long format to a wide format, which can be particularly useful for data analysis and visualization.
</p>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    <i>Syntax:</i><br>
    <code>df.pivot(index=None, columns=None, values=None)</code>
</p>

<ul style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: square;">
    <li><b>index:</b> The column to use to make the new frame’s index.</li>
    <li><b>columns:</b> The column to use to make the new frame’s columns.</li>
    <li><b>values:</b> The column to use for populating the new frame’s values. If not specified, all remaining columns will be used.</li>
</ul>
sed.</li>
</ul>

In [26]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [32, 75, 30, 77]
})

df

         Date         City  Temperature
0  2024-01-01     New York           32
1  2024-01-01  Los Angeles           75
2  2024-01-02     New York           30
3  2024-01-02  Los Angeles           77

In [27]:
# Pivot the DataFrame
pivot_df = df.pivot(index='Date', columns='City', values='Temperature')

# Display the result
pivot_df

City        Los Angeles  New York
Date
2024-01-01           75        32
2024-01-02           77        30

In [28]:
import pandas as pd

# Create a sample DataFrame of sales transactions
data = {
    'Sales_Rep': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'Region': ['East', 'East', 'West', 'West', 'East', 'West'],
    'Sales': [3000, 2000, 4500, 5000, 3500, 1500]
}
df = pd.DataFrame(data)
print("--- Raw DataFrame ---")
print(df)

--- Raw DataFrame ---
  Sales_Rep Region  Sales
0     Alice   East   3000
1       Bob   East   2000
2     Alice   West   4500
3       Bob   West   5000
4     Alice   East   3500
5       Bob   West   1500

In [30]:
df.pivot_table(index='Sales_Rep', columns='Region', values='Sales', aggfunc='sum')

Region     East  West
Sales_Rep
Alice      6500  4500
Bob        2000  6500

In [32]:
df.pivot_table(index='Sales_Rep', columns='Region', values='Sales', aggfunc='mean')

Region     East  West
Sales_Rep
Alice      3250  4500
Bob        2000  3250

In [33]:
df.pivot_table(index='Sales_Rep', columns='Region', values='Sales', aggfunc=['sum', 'mean'], margins=True)

            sum                       mean
Region     East   West    All         East         West          All
Sales_Rep
Alice      6500   4500  11000  3250.000000  4500.000000  3666.666667
Bob        2000   6500   8500  2000.000000  3250.000000  2833.333333
All        8500  11000  19500  2833.333333  3666.666667  3250.000000

# <h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: left; margin:-60px 0 0 0; padding-bottom: 10px; border-bottom: 2px solid #264653;"> Pandas GroupBy </h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 20px;">
    The <code>groupby</code> method in Pandas is used to group data based on one or more columns and perform operations on these groups. This is useful for aggregating and summarizing data.
</p>

<h3 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 20px; margin-top: 20px;">
    Syntax:
</h3>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; margin-top: 10px;">
    <code>df.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, dropna=True)</code>
</p>

<h3 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 20px; margin-top: 20px;">
    Parameters:
</h3>
<ul style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: square;">
    <li><b>by:</b> The column(s) to group by. It can be a column name, list of column names, or a function.</li>
    <li><b>axis:</b> The axis to group along (default is 0 for rows).</li>
    <li><b>level:</b> If the axis is a MultiIndex (hierarchical), group by a particular level.</li>
    <li><b>as_index:</b> Whether to set the group labels as the index (default is True).</li>
    <li><b>sort:</b> Whether to sort the group labels (default is True).</li>
    <li><b>group_keys:</b> Whether to include group keys in the result (default is True).</li>
    <li><b>dropna:</b> Whether to drop groups with missing values (default is True).</li>
</ul>

<h3 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 20px; margin-top: 20px;">
    Examples:
</h3>
<ul style="font-family: 'Candara', sans-serif; font-size: 18px; line-height: 1.8; padding-left: 20px; margin-top: 10px; list-style-type: square;">
    <li><b>Basic GroupBy:</b><br>
        <code>df.groupby('column_name').mean()</code> - Groups by a single column and calculates the mean of each group.</li>
    <li><b>Multiple Columns:</b><br>
        <code>df.groupby(['column1', 'column2']).sum()</code> - Groups by multiple columns and calculates the sum of each group.</li>
    <li><b>Custom Aggregation:</b><br>
        <code>df.groupby('column_name').agg({'column_to_aggregate': 'sum'})</code> - Applies custom aggregation functions.</li>
</ul>
om aggregation functions.</li>
</ul>

In [34]:
import pandas as pd


# Sample DataFrame
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40, 50, 60]
})

df

  Category  Value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        B     60

In [35]:
# df.groupby(['column1', 'column2']).sum()
df.groupby(['Category']).count()

          Value
Category
A             3
B             3

In [36]:
# Group by 'Category' and calculate the mean of 'Value'
# df.groupby(['column1', 'column2']).sum()

grouped_df = df.groupby('Category').mean()

# Display the result
grouped_df

          Value
Category
A          30.0
B          40.0

In [39]:
'''Reshaping using Stack'''
import pandas as pd
file_path = "D:/Old Projects/MLProjects/ZDatasets/DummyData/Data_Train1.csv"
df = pd.read_csv(file_path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Airfare,Full Name
0,Rajesh,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,8715.10,Ram-Kumar
1,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,8715.10,Ram-Kumar
2,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,0.00,Mohan-Sharma
3,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,6995.55,Tina-Ali
4,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
5,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari
6,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,7840.56,Jeetu-Gandhi
7,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,7813.89,Meera-Kumari

In [ ]:
# some functions

In [74]:
import pandas as pd
file_path = "D:\\MLProjects\\ZDatasets\\DummyData\\file.xlsx"
df = pd.read_excel(file_path)
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,2019-06-09,09:25:00,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,2019-05-12,18:05:00,23:30:00,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,2019-03-01,16:50:00,21:35:00,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,2019-03-12,10:25:00,18:55:00,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,2019-03-01,05:05:00,08:00:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [75]:
df.head(2)

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,2019-03-24,22:20:00,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,2019-05-01,05:50:00,13:15:00,5,50,13,15,Mohan-Sharma

In [76]:
df.tail(2)

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,2019-03-12,08:55:00,10:25:00,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,2019-05-27,11:25:00,19:15:00,11,25,19,15,Sunita-Patil

In [80]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'Temperature': [32, 75, 30, 77]
})

df

         Date         City  Temperature
0  2024-01-01     New York           32
1  2024-01-01  Los Angeles           75
2  2024-01-02     New York           30
3  2024-01-02  Los Angeles           77

In [81]:
# Pivot the DataFrame
pivot_df = df.pivot(index='Date', columns='City', values='Temperature')

# Display the result
pivot_df

City        Los Angeles  New York
Date
2024-01-01           75        32
2024-01-02           77        30

<h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: center; padding-bottom: 10px; border-bottom: 2px solid #264653;">
    Pandas GroupBy
</h2><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pandas GroupBy</title>
<style>
.color-primary { color: #2a9d8f; } /* Teal/Green */
.color-secondary { color: #264653; } /* Dark Blue/Gray */
.font-candara { font-family: 'Candara', sans-serif; }
body { font-family: 'Candara', sans-serif; color: #264653; line-height: 1; margin:0; padding:0; }
pre { background:#f0f0f0; padding:5px; border-radius:3px; margin:0; }
code { font-family: monospace; }
</style>
</head>
<body>

<h2 style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-weight: bold; text-align: left; padding-bottom: 10px; border-bottom: 2px solid #264653;">
Pandas GroupBy
</h2>

<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 15px; line-height:1; margin-top: 0;">
The <code>groupby</code> method in Pandas is used to group data based on one or more columns and perform operations on these groups. It is useful for aggregating and summarizing data.
</p>

<ol style="font-family: 'Candara', sans-serif; font-size: 15px; line-height:1; padding-left: 20px; margin-top: 0; list-style-type: none;">
<li style="color: #2a9d8f; margin-bottom: 0;">
<b>Basic GroupBy</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
Group by a single column and calculate the mean of each group.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
<i>Example:</i> <code>df.groupby('column_name').mean()</code>
</p>
</li>

<li style="color: #2a9d8f; margin-bottom: 0;">
<b>Multiple Columns</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
Group by multiple columns and calculate the sum of each group.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
<i>Example:</i> <code>df.groupby(['column1', 'column2']).sum()</code>
</p>
</li>

<li style="color: #2a9d8f; margin-bottom: 0;">
<b>Custom Aggregation</b>
<p style="color: #264653; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
Use custom aggregation functions on a group.
</p>
<p style="color: #2a9d8f; font-family: 'Candara', sans-serif; font-size: 14px; margin: 0; line-height:1;">
<i>Example:</i> <code>df.groupby('column_name').agg({'column_to_aggregate': 'sum'})</code>
</p>
</li>
</ol>

<h3 style="color: #2a9d8f; font-family: 'Candara', sans-serif; margin-top: 0;">Syntax</h3>
<pre style="line-height:1;">df.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, dropna=True)</pre>

<h3 style="color: #2a9d8f; font-family: 'Candara', sans-serif; margin-top: 0;">Parameters</h3>
<ul style="font-family: 'Candara', sans-serif; font-size: 14px; line-height:1;">
<li><b>by:</b> Column(s) to group by. Can be a column name, list of column names, or a function.</li>
<li><b>axis:</b> Axis to group along (default 0 for rows).</li>
<li><b>level:</b> If axis has a MultiIndex, group by a particular level.</li>
<li><b>as_index:</b> Whether to set the group labels as the index (default True).</li>
<li><b>sort:</b> Whether to sort the group labels (default True).</li>
<li><b>group_keys:</b> Whether to include group keys in the result (default True).</li>
<li><b>dropna:</b> Whether to drop groups with missing values (default True).</li>
</ul>

</body>
</html>
efault True).</li>
</ul>

</body>
</html>
p groups with missing values (default True).</li>
</ul>

</body>
</html>

om aggregation functions.</li>
</ul>

In [84]:
import pandas as pd


# Sample DataFrame
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40, 50, 60]
})

df

  Category  Value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        B     60

In [91]:
# df.groupby(['column1', 'column2']).sum()
df.groupby(['Category']).count()

          Value
Category
A             3
B             3

In [ ]:
# Group by 'Category' and calculate the mean of 'Value'
# df.groupby(['column1', 'column2']).sum()

grouped_df = df.groupby('Category').mean()

# Display the result
grouped_df

# String Handling:

# Counting and Length:

df['First_name']

False
False

In [ ]:
df['First_name'].str.

In [ ]:
df['First_name'].str.len()

# Counting and count:

In [ ]:
df['First_name'].str.count('Ram')

In [ ]:
# String Searching and Matching:

In [ ]:
df['First_name'].str.contains('am')

In [ ]:
# StartWith
df[df['First_name'].str.startswith('M')]

In [ ]:
# endwith
df[df['First_name'].str.endswith('l')]

In [ ]:
# Substitution and Replacement:

df['City'].str.replace("BANGALURU","BLR")

In [ ]:
df['Full Name']

In [ ]:
# Splitting and Joining:

In [ ]:
df['Full Name'].str.split("-",expand=True)

In [ ]:
df['Full Name'].str.rsplit("-",expand=True)

In [ ]:
'''Make a column of dataframe as index with remove default index.'''
newDict = {'Date'           :['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
            'Product'       :[' UMbreLla', '  maTtress', 'BaDmintoN ', 'Shuttle'],
            'Price'         :[1250, 1450, 1550, 400],
            'Discount'      :[10, 8, 15, 10]}

df1=pd.DataFrame(newDict)
print(df1)

'''Make a column of dataframe as index with remove default index.'''
newDict = {'Date'           :['10/2/2012', '11/2/2011', '12/2/2011', '13/2/2011'],
            'Product'       :[' WaterBottle', '  maTtress', 'BaDmintoN ', 'Shuttle'],
            'Price'         :[125, 1450, 1550, 400],
            'Discount'      :[10, 8, 15, 10]}

df2=pd.DataFrame(newDict)
print(df2)

In [ ]:
df1

In [ ]:
df3 = df2.loc[:,['Product','Price']]
df3

In [ ]:
df1
df3

# Home Work

| Function           | Description                                               |
|--------------------|-----------------------------------------------------------|
| `str.lower()`      | Convert strings to lowercase.                            |
| `str.upper()`      | Convert strings to uppercase.                            |
| `str.title()`      | Capitalize the first letter of each word.                 |
| `str.strip()`      | Remove leading and trailing whitespace.                   |
| `str.replace()`    | Replace occurrences of a substring with another substring.|
| `str.contains()`   | Check if strings contain a specified substring.           |
| `str.startswith()` | Check if strings start with a specified substring.        |
| `str.endswith()`   | Check if strings end with a specified substring.          |
| `str.split()`      | Split strings around a specified delimiter.               |
| `str.get()`        | Get a specific element from a split string.               |
| `str.len()`        | Compute the length of each string.                        |
| `str.findall()`    | Find all occurrences of a pattern in each string.         |
| `str.extract()`    | Extract patterns from strings using regular expressions.  |
| `str.join()`       | Join elements of a list-like object with a specified separator. |
| `str.zfill()`      | Pad strings with zeros on the left to a specified width.  |
| `str.extractall()` | Extract all matches of a pattern from strings.            |
| `str.replace()` with regex | Replace using regular expressions.                 |
| `str.count()`      | Count the number of occurrences of a substring in each string. |
| `str.get_dummies()`| Convert categorical variable(s) into dummy/indicator variables. |
| `str.pad()`        | Pad strings with a specified character to a specified width. |
| `str.isalpha()`    | Check if all characters in each string are alphabetic.    |
| `str.isdigit()`    | Check if all characters in each string are digits.        |
| `str.isnumeric()`  | Check if all characters in each string are numeric characters. |
| `str.isspace()`    | Check if all characters in each string are whitespace characters. |
| `str.islower()`    | Check if all characters in each string are lowercase.      |
| `str.isupper()`    | Check if all characters in each string are uppercase.      |
| `str.normalize()`  | Normalize unicode characters in each string.              |
| `str.rsplit()`     | Split strings from the right around a specified delimiter.|
| `str.slice()`      | Slice strings based on start and stop positions.          |
| `str.splitexpand()`| Split strings into separate columns and expand them into a DataFrame. |
| `str.removeprefix()` | Remove a specified prefix from each string if it exists. |
| `str.removesuffix()` | Remove a specified suffix from each string if it exists. |