In [ ]:
# Load the File

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("CorporateSalary.xlsx")

df

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200
2,Manager,Bachelor's,Engineering,3.9,14,2.7,139400
3,Lead Consultant,Master's,Data Science,5.3,13,2.7,137200
4,Junior Analyst,PhD,HR,3.4,15,5.0,90100
...,...,...,...,...,...,...,...
95,Senior Analyst,Bachelor's,Sales,9.8,15,5.0,118200
96,Lead Consultant,Master's,Engineering,9.9,14,3.9,146800
97,Senior Analyst,PhD,Engineering,7.7,9,4.4,126200
98,Junior Analyst,PhD,Engineering,9.9,11,4.9,117800
99,Junior Analyst,Master's,Marketing,8.0,10,4.6,89600

In [6]:
# split in to X and y

y = df[['Salary']]

X  = df.drop(['Salary'],axis=1)
y
X

    Salary
0   119300
1   212200
2   139400
3   137200
4    90100
..     ...
95  118200
96  146800
97  126200
98  117800
99   89600

[100 rows x 1 columns]

In [9]:
# Train test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
ordinalColumns = ['Designation','Education']

Designation_Order = ['Junior Analyst','Senior Analyst','Lead Consultant', 'Manager','Senior Manager','Director']
Education_Order = ["Bachelor's", "Master's", 'PhD']
OneHotColuns = ['Department']
numColumns = ['TenureYears','ProjectsCompleted','PerformanceScore']

In [ ]:
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

In [18]:
df

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200
2,Manager,Bachelor's,Engineering,3.9,14,2.7,139400
3,Lead Consultant,Master's,Data Science,5.3,13,2.7,137200
4,Junior Analyst,PhD,HR,3.4,15,5.0,90100
...,...,...,...,...,...,...,...
95,Senior Analyst,Bachelor's,Sales,9.8,15,5.0,118200
96,Lead Consultant,Master's,Engineering,9.9,14,3.9,146800
97,Senior Analyst,PhD,Engineering,7.7,9,4.4,126200
98,Junior Analyst,PhD,Engineering,9.9,11,4.9,117800
99,Junior Analyst,Master's,Marketing,8.0,10,4.6,89600