# Data Reading

In [175]:
import pandas as pd

def readFile():
     df = pd.read_csv("E:/1.Eathans/Ethans/Data/Airline/Airline1.csv")
     return df

#  Cleaning

In [176]:
df.describe()

                 ID         Price   DurHrs_Mins
count  10683.000000  10683.000000  10683.000000
mean    5342.000000   9087.219176    643.180286
std     3084.060797   4611.065933    507.875177
min        1.000000   1759.000000      5.000000
25%     2671.500000   5277.000000    170.000000
50%     5342.000000   8372.000000    520.000000
75%     8012.500000  12373.000000    930.000000
max    10683.000000  79512.000000   2860.000000

In [177]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               10683 non-null  int64
 1   Airline          10683 non-null  str
 2   Date_of_Journey  10683 non-null  str
 3   Source           10683 non-null  str
 4   Destination      10683 non-null  str
 5   Route            10683 non-null  str
 6   Dep_Time         10683 non-null  str
 7   Arrival_Time     10683 non-null  str
 8   Duration         10683 non-null  str
 9   Total_Stops      10683 non-null  str
 10  Additional_Info  10683 non-null  str
 11  Price            10683 non-null  float64
 12  DurHrs_Mins      10683 non-null  int64
dtypes: float64(1), int64(2), str(10)
memory usage: 2.1 MB

In [178]:
df.isnull().sum()

ID                 0
Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
DurHrs_Mins        0
dtype: int64

# Source,Destination,Route,Total_Stops,Price

In [179]:
df[df['Price'].isnull()]

def Handel_Missing(df):
    missin_COL = ['Source','Destination','Route','Total_Stops']
    for i in missin_COL:
        Missing = df[i].mode()[0]
        df.fillna({i:Missing},inplace=True)
        
    Missing_Price = df['Price'].mean()
    df.fillna({'Price':Missing_Price},inplace=True)
    return df
Handel_Missing(df)
df.isnull().sum()

ID                 0
Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
DurHrs_Mins        0
dtype: int64

# Handle Duplicates

In [180]:
def Handle_Duplicates(df):
    df.drop_duplicates(inplace=True)
    df[df.duplicated()]
    return df
Handle_Duplicates(df)

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,DurHrs_Mins
0,1,IndiGo,24-03-2019 22:20,Banglore,Delhi,BLR _ DEL,22:20,25-03-2019 01:10,2h 50m,non-stop,No info,3897.0,170
1,2,Air India,01-05-2019 05:50,Kolkata,Banglore,CCU _ IXR _ BBI _ BLR,05:50,01-05-2019 13:15,7h 25m,2 stops,No info,7662.0,445
2,3,Jet Airways,09-06-2019 09:25,Delhi,Cochin,DEL _ LKO _ BOM _ COK,09:25,10-06-2019 04:25,19h 00m,2 stops,No info,13882.0,1140
3,4,IndiGo,12-05-2019 18:05,Kolkata,Banglore,CCU _ NAG _ BLR,18:05,12-05-2019 23:30,5h 25m,1 stop,No info,6218.0,325
4,5,IndiGo,01-03-2019 16:50,Banglore,Delhi,BLR _ NAG _ DEL,16:50,01-03-2019 21:35,4h 45m,1 stop,No info,13302.0,285
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,10679,Air Asia,09-04-2019 19:55,Kolkata,Banglore,CCU ? BLR,19:55,09-04-2019 22:25,2h 30m,non-stop,No info,4107.0,150
10679,10680,Air India,27-04-2019 20:45,Kolkata,Banglore,CCU ? BLR,20:45,27-04-2019 23:20,2h 35m,non-stop,No info,4145.0,155
10680,10681,Jet Airways,27-04-2019 08:20,Banglore,Delhi,BLR ? DEL,08:20,27-04-2019 11:20,3h 00m,non-stop,No info,7229.0,180
10681,10682,Vistara,01-03-2019 11:30,Banglore,Delhi,BLR ? DEL,11:30,01-03-2019 14:10,2h 40m,non-stop,No info,12648.0,160
10682,10683,Air India,09-05-2019 10:55,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,09-05-2019 19:15,8h 20m,2 stops,No info,11753.0,500

In [181]:
df[df.duplicated()]

Empty DataFrame
Columns: [ID, Airline, Date_of_Journey, Source, Destination, Route, Dep_Time, Arrival_Time, Duration, Total_Stops, Additional_Info, Price, DurHrs_Mins]
Index: []

# Handle unever Values

In [182]:
df['Destination'].value_counts()
def Replace_Uneve(df):
    df['Destination'] = df['Destination'].replace({"New Delhi":"Delhi"})
    return df
Replace_Uneve(df)

df['Destination'].value_counts()

Destination
Cochin       4538
Banglore     2871
Delhi        2196
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [ ]:


def convertDur_Min(df):
    for i in df.index:
        ColOne = df.loc[i,'Duration'].split()[0]
        ColTwo = df.loc[i,'Duration'].split()[1]
        
        if "h" in ColOne:
            ColOne = int(ColOne.replace("h",""))*60
        elif "m" in ColOne:
            ColOne = int(ColOne.replace("m",""))

        if "h" in ColTwo:
            ColTwo = int(ColTwo.replace("h",""))*60
        elif "m" in ColTwo:
            ColTwo = int(ColTwo.replace("m",""))
        
        df.loc[i,'DurHrs_Mins'] = ColOne + ColTwo
    return df

In [ ]:
readFile()
df = Handel_Missing(df)
df = Handle_Duplicates(df)
df = Replace_Uneve(df)
df = convertDur_Min(df)

df

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,DurHrs_Mins
0,1,IndiGo,24-03-2019 22:20,Banglore,Delhi,BLR _ DEL,22:20,25-03-2019 01:10,2h 50m,non-stop,No info,3897.0,170
1,2,Air India,01-05-2019 05:50,Kolkata,Banglore,CCU _ IXR _ BBI _ BLR,05:50,01-05-2019 13:15,7h 25m,2 stops,No info,7662.0,445
2,3,Jet Airways,09-06-2019 09:25,Delhi,Cochin,DEL _ LKO _ BOM _ COK,09:25,10-06-2019 04:25,19h 00m,2 stops,No info,13882.0,1140
3,4,IndiGo,12-05-2019 18:05,Kolkata,Banglore,CCU _ NAG _ BLR,18:05,12-05-2019 23:30,5h 25m,1 stop,No info,6218.0,325
4,5,IndiGo,01-03-2019 16:50,Banglore,Delhi,BLR _ NAG _ DEL,16:50,01-03-2019 21:35,4h 45m,1 stop,No info,13302.0,285
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,10679,Air Asia,09-04-2019 19:55,Kolkata,Banglore,CCU ? BLR,19:55,09-04-2019 22:25,2h 30m,non-stop,No info,4107.0,150
10679,10680,Air India,27-04-2019 20:45,Kolkata,Banglore,CCU ? BLR,20:45,27-04-2019 23:20,2h 35m,non-stop,No info,4145.0,155
10680,10681,Jet Airways,27-04-2019 08:20,Banglore,Delhi,BLR ? DEL,08:20,27-04-2019 11:20,3h 00m,non-stop,No info,7229.0,180
10681,10682,Vistara,01-03-2019 11:30,Banglore,Delhi,BLR ? DEL,11:30,01-03-2019 14:10,2h 40m,non-stop,No info,12648.0,160
10682,10683,Air India,09-05-2019 10:55,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,09-05-2019 19:15,8h 20m,2 stops,No info,11753.0,500