In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("Data_Raw\Classification_LoanSanction.xlsx")
df.head(2)

,ID,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Loans,Education,Employment_Stability,Credit_Risk,Gender,Employment_Type,Marital_Status,Property_Ownership,Loan_Sanctioned
0,1,24,28000,580,150000,1,2,High School,Low,High,Male,Salaried,Single,Rented,0
1,2,35,55000,720,300000,8,0,Graduate,High,Low,Female,Salaried,Married,Owned,1

In [5]:
df = df.drop(['ID','Credit_Risk'],axis=1)

df

,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Loans,Education,Employment_Stability,Gender,Employment_Type,Marital_Status,Property_Ownership,Loan_Sanctioned
0,24,28000,580,150000,1,2,High School,Low,Male,Salaried,Single,Rented,0
1,35,55000,720,300000,8,0,Graduate,High,Female,Salaried,Married,Owned,1
2,42,68000,745,450000,14,1,Postgraduate,High,Male,Salaried,Married,Owned,1
3,29,40000,635,280000,4,2,Graduate,Medium,Female,Self-employed,Single,Rented,0
4,51,90000,790,600000,22,0,Postgraduate,High,Male,Business,Married,Owned,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,49,85000,780,560000,21,0,Postgraduate,High,Female,Business,Married,Owned,1
196,40,65000,710,380000,12,1,Graduate,High,Male,Salaried,Married,Owned,1
197,31,45000,635,280000,5,2,Graduate,Low,Female,Self-employed,Single,Rented,0
198,52,93000,800,620000,24,0,Postgraduate,High,Male,Business,Married,Owned,1
199,27,33000,590,170000,2,1,High School,Low,Female,Salaried,Single,Rented,0

In [6]:
# Split data in to X and y

X = df.drop('Loan_Sanctioned',axis=1)
X
y = df['Loan_Sanctioned']

y

X

,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Loans,Education,Employment_Stability,Gender,Employment_Type,Marital_Status,Property_Ownership
0,24,28000,580,150000,1,2,High School,Low,Male,Salaried,Single,Rented
1,35,55000,720,300000,8,0,Graduate,High,Female,Salaried,Married,Owned
2,42,68000,745,450000,14,1,Postgraduate,High,Male,Salaried,Married,Owned
3,29,40000,635,280000,4,2,Graduate,Medium,Female,Self-employed,Single,Rented
4,51,90000,790,600000,22,0,Postgraduate,High,Male,Business,Married,Owned
...,...,...,...,...,...,...,...,...,...,...,...,...
195,49,85000,780,560000,21,0,Postgraduate,High,Female,Business,Married,Owned
196,40,65000,710,380000,12,1,Graduate,High,Male,Salaried,Married,Owned
197,31,45000,635,280000,5,2,Graduate,Low,Female,Self-employed,Single,Rented
198,52,93000,800,620000,24,0,Postgraduate,High,Male,Business,Married,Owned
199,27,33000,590,170000,2,1,High School,Low,Female,Salaried,Single,Rented

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.20,random_state=42)

In [8]:

X_train.to_excel("Data_Train_Test/X_train.xlsx",index=False)
X_test.to_excel("Data_Train_Test/X_test.xlsx",index=False)
y_train_true.to_excel("Data_Train_Test/y_train_true.xlsx",index=False)
y_test_true.to_excel("Data_Train_Test/y_test_true.xlsx",index=False)

In [ ]:
X_test

In [9]:
X_test.head(2)

,Age,Income,Credit_Score,Loan_Amount,Employment_Years,Existing_Loans,Education,Employment_Stability,Gender,Employment_Type,Marital_Status,Property_Ownership
95,43,76000,765,480000,15,0,Postgraduate,High,Female,Business,Married,Owned
15,26,32000,595,180000,2,2,High School,Low,Male,Salaried,Single,Rented

In [10]:
#Numerical Columns
Numeric_Col = ['Age','Income','Credit_Score','Loan_Amount','Employment_Years','Existing_Loans']
#Categorical
#   Ordinal Columns
Ordinal_Col = ['Education','Employment_Stability']

Education_Seq = ['High School', 'Graduate', 'Postgraduate']
Employment_Stability_Seq = ['Low', 'Medium', 'High']

#Onehot
#Onehot_Col = ['Employment_Type']
Onehot_Col = ['Gender','Employment_Type','Marital_Status','Property_Ownership']

In [11]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

Ordinal_Encoding = ('Ordinal_Encoding',OrdinalEncoder(categories=[Education_Seq, Employment_Stability_Seq]),Ordinal_Col,)
OneHot_Encoding =  ('OneHot_Encoding',OneHotEncoder(sparse_output=False,drop="first", handle_unknown="ignore"),Onehot_Col,)
Scaling = ("Scaling", StandardScaler(), Numeric_Col)



from sklearn.compose import ColumnTransformer

trans_Obj = ColumnTransformer(
        transformers=[Ordinal_Encoding,OneHot_Encoding,Scaling]).set_output(transform="pandas")

In [12]:
X_train_trans = trans_Obj.fit_transform(X_train)
X_train_trans.to_excel("Data_Trans/X_train_trans.xlsx",index=False)

In [ ]:
X_train_trans

In [14]:
# Save Transform.PKL 
import joblib
joblib.dump(trans_Obj,"Trans_File/transform.pkl")

['Trans_File/transform.pkl']

In [15]:
# Import the Transform.pkl

transform_Obj_01 = joblib.load("Trans_File/transform.pkl")

In [16]:
# Transform the X_test
X_test_trans = transform_Obj_01.fit_transform(X_test)

In [17]:
X_test_trans.to_excel("Data_Trans/X_test_trans.xlsx",index=False)